### ISSUE TITLE
No operation available for full or partial text search

### ISSUE THREAD

**Issue by youngnishant** [datastax/astrajs#16]
I was trying to implement search query so i was not able to find the implementation of full text search or partial text search using collection api, Please help me to implement small search query using @astra/collections or rest api's.
Thank you

**Comment by kidrecursive** [comment]
To execute a search, you can use the `find()` function on a collection like so:
```javascript
const docs = await testCollection.find({
        firstName: { $eq: "Cliff" },
      });
```
The parameter that you pass is the `where` clause.

More information on searching can be found here: https://stargate.io/docs/stargate/1.0/developers-guide/document-using.html#_reading_documents

**Comment by youngnishant** [comment]
@kidrecursive i want to write a query to return all the names that starts with 'cliff' and output can be like this:-
Cliffjunior
Cliffhigh

**Comment by kidrecursive** [comment]
I see, I believe wildcards are available for keys on documents but not on values, so doing a search in the way you are describing isn't supported on documents yet (`Cliff*` for example).
