### ISSUE TITLE
Tests in restClient are using Documents API

### ISSUE THREAD

**Issue by dougwettlaufer** [datastax/astrajs#17]
All of the tests in [rest.test.js](https://github.com/datastax/astrajs/blob/master/packages/rest/src/rest.test.js) are testing the Documents API (`/namespaces`) instead of the REST API (`/keyspaces`).

**Comment by kidrecursive** [comment]
Yes, that's true, I have some more tests in the 0.1.X branch that cover the namespaces group, will have that merged in a bit.
