### ISSUE TITLE
Request failed with status code 404 with REST API

### ISSUE THREAD

**Issue by bitsnaps** [datastax/astrajs#18]
Hello,

* The following queries work fine using the Document API:
```js
    const restClient = await createClient({
      astraDatabaseId: process.env.ASTRA_DB_ID,
      astraDatabaseRegion: process.env.ASTRA_DB_REGION,
      applicationToken: process.env.ASTRA_DB_APPLICATION_TOKEN
    });
    const basePath = `/api/rest/v2/namespaces/${process.env.ASTRA_DB_KEYSPACE}/collections/users`;
    const { data, status } = await restClient.get(`${basePath}`, {});
```
The equivalent requests should return the same results using `basePath` (where the `members` here is a table, and `users` is a collection):
```js
const basePath = `/api/rest/v2/keyspaces/${process.env.ASTRA_DB_KEYSPACE}/members`;
```
The docs uses the path `/collections/members` which throws the error: `Request failed with status code 404`... right?

1- The first request returns only one document, shouldn't be returning all documents?

* The following `axios` requests work fine for both queries (Document API & REST API):
```js
    const axios = require('axios');
    //...

    let members = [];

    const instance = axios.create({
      // Document API
      // baseURL: `https://${process.env.ASTRA_DB_ID}-${process.env.ASTRA_DB_REGION}.apps.astra.datastax.com/api/rest/v2/namespaces/${process.env.ASTRA_DB_KEYSPACE}/collections/`,
      // REST API
      baseURL: `https://${process.env.ASTRA_DB_ID}-${process.env.ASTRA_DB_REGION}.apps.astra.datastax.com/api/rest/v2/keyspaces/${process.env.ASTRA_DB_KEYSPACE}/`,
      timeout: 30000,
      headers: {
        'X-Cassandra-Token': process.env.ASTRA_DB_APPLICATION_TOKEN,
        'Content-Type': 'application/json'
      }
    })

    // members = await instance.get('users') // Document API (only one document returned)
    // members = await instance.get('users/5ea53e52-dd0c-49af-82c2-f3e210530e2f') // Document API
    members = await instance.get('members/5ea53e52-dd0c-49af-82c2-f3e210530e2f') // REST API
      .then((results) => {
        return results.data;
      });
```
2- Where `users` is a document (no predefined schema), and `members` is a cassandra table (schema previously defined), however, in both queries there is no way to get the list of collection (or rows), they always return only the first document (unless the id specified), is there any way to retrieve all rows?
P.S. The `results.data` contains `data` as an array of object, so we you must use `result.data.data` to get the array back from results which is weird, is that behavior expected?

Regards

**Comment by kidrecursive** [comment]
Heya, when querying document collections that haven't been written to yet, you will get a `404`. 

The default page size from the `GET` is `1`, so that is why you are only seeing one result. You can increase this with the url parameter `page-size=20`

`result.data.data` is expected, the request body has the data wrapped in a key called `data`. You can remove this if desired with the url parameter `raw =true`

Have a nice day!

**Comment by bitsnaps** [comment]
Thank you Chris, the only tricky param was `page-state` not really obvious one!
