### ISSUE TITLE
pageState property not available in response

### ISSUE THREAD

**Issue by tom-kuppinen-datastax** [datastax/astrajs#22]
When using the nodejs library for searching documents, the pageState property is not returned.  Without this property you can not page a larger result set.  It is available via the API, please see attached 

![image](https://user-images.githubusercontent.com/87655429/137746494-a96f26ac-3a82-409b-9642-ed208c765971.png)

**Comment by adamfortuno** [comment]
I ran into the same problem. If I was returning a result set with more than 20 documents, how do we page through the result set?

Here is what I tried...

1. Login to the Astra console.
2. Create a new database and keyspace.
3. Create a token with Database Administrator rights and save the token value.
4. From a command prompt, create a directory.
5. Navigate into the directory and initialize it: `npm init`.
6. Install the `@astrajs/collections` module; `npm install @astrajs/collections`.
7. Install the `@astrajs/collections` module; `npm install uuid`.
8. Create a script with the following contents (adjust *** values):

  ```javascript
  const uuid = require('uuid')
  const { createClient } = require("@astrajs/collections")
  
  
  async function init() {
      const max_user_count = 1
      
      const name_namespace = '******'
      const name_collection = 'things'
  
      try {
          // Create a connection to `thinger`
          const client = await createClient({
              astraDatabaseId: "***",
              astraDatabaseRegion: "******",
              applicationToken: "***",
          })
  
          // Create a namespace and document collection
          const collection = client.namespace(name_namespace).collection(name_collection)
          
          // Dump a bunch of documents in the collection
          for (user_count = 0; user_count < max_user_count; user_count++) {
              const user = await collection.create({ name: uuid.v4(), })
          }
  
          // Pull back all documents - limited to the default of 20 per page
          const results = await collection.find({})
          //const results = await collection.find({}, {"page-size": 15})
          
          // How do we page through the result sets?
          console.log(results)
  
      } catch(error) {
          console.log(error)
      }
  };
  
  init()
  ```
9. Run the script: `node ./script-name.js`.

I could trim the results to fewer docs. I couldn't get more than 20-docs.

**OS:**
 - ProductName:	macOS
 - ProductVersion:	11.6
 - BuildVersion:	20G165

**Environment:**
 - Node.js v14.16.1
 - @astrajs/rest v0.2.1
