### ISSUE TITLE
Document API does not work with Next.js API Routes

### ISSUE THREAD

**Issue by adherb** [datastax/astrajs#6]
Hello,
I am unable to get the document api to work with the Next.js api routes, I can get it to work in a node environment or using Netlify Functions, but not using Next.js API routes.

Here us the error I am receiving:
Error: @astrajs/rest: baseUrl required for initialization

Any help would be much appreciated.

Thanks,
Adam

**Comment by kidrecursive** [comment]
Hey Adam, when you're running using the Next.js API routes, are your Astra credentials set as environment variables?

**Comment by adherb** [comment]
Hey Chris,

yes they are, I have the following set in my local.env file:

ASTRA_DB_ID=
ASTRA_DB_REGION=
ASTRA_DB_USERNAME=
ASTRA_DB_APPLICATION_TOKEN=
ASTRA_DB_KEYSPACE=

and I'm accessing them here in the api route:

const astraClient = await createClient({
        astraDatabaseId: process.env.ASTRA_DB_ID,
        astraDatabaseRegion: process.env.ASTRA_DB_REGION,
        applicationToken: process.env.ASTRA_DB_APPLICATION_TOKEN,
    })

**Comment by adherb** [comment]
I've created a quick example - next-datastax

The api route is /page/api/create-user

The form is at /pages/index

**Comment by adherb** [comment]
Chris, I'm sorry to waste your time.

I have just realised in my env.local file I wrote us-east1 instead of us-east-1, it now works perfectly.

My apologies, I spent a good 3 days trying to debug that before I reached out. I could have swore I copy and pasted all of those codes.

Anyway, I will build a simple crud app for people looking to get started with next.js and the new document api.
