### ISSUE TITLE
Created collections not reflecting in db

### ISSUE THREAD

**Issue by adherb** [datastax/astrajs#8]
Hi Chris,

I've created a Next.js api route that creates a user in a users collection using the document api. I also have an api route that gets all users and displays them. 

I have realised that when I create a new user the users is not always shown on the get users api routes. I have logged into my Datastax account and the new users information is not reflected in the CQL terminal when I query the users collection.

What's interesting is approx 1/5 users reflects on my get users route (and in the Datastax CQL terminal). In the api routes I have both the connection to the database and the create function wrapped in seperate try catch block and I am receiving not errors.

What is even more interesting is that I have an if check in the api route to see if the email entered is already in use prior to a new user being created, when I try and reuse one of the emails from the accounts that I cannot see on the get route, I hit my custom response "Email already in use".

Do you have any idea why this could be? I have been creating many usres with random strings quickly as I'm testing a custom stripe sign up flow.

Thanks,
Adam

**Comment by kidrecursive** [comment]
Heya Adam, I'm not sure why you would get this behavior, there is a debug mode (debug: true) on the collections connection that will echo out reqs/responses for you, that may be helpful. 

Be advised, the CQL console (may) give you unexpected data as the document structure is spread out across columns.

Because your code is getting an already in use, but not showing up in a `find({})` call, can you try just finding that one user by email? Also, each find call is paged, you can increase the page size or page through results with additional parameters there.

Let me know if any of this helps, happy to help debug further if I can.

**Comment by adherb** [comment]
Hi Chris,

Thanks for getting back to me. Great, I will have a go with the debugger.

I just had a thought:

Due to the fact that the if check for if the email already exists works, I think it may be an issue with my get request.

When I try and get all users using the following code it only returns 20 users:

 const user = await users.find({});

But when I search for a missing user using the following code, it finds and displays them correctly:

const user = await users.findOne({ email: { $eq: "afsswggdswdsqeg@hhdheed.com" } });

Is it possible that the first request is set to a return limit of 20? Similar to how the Wordpress api defaults to return only 10 posts.

If so is there a way I can get set it to return all users?

**Comment by kidrecursive** [comment]
Yes, that is correct, the default page size is 20, you can increase this to 100 with a query like this:

`const users = await users.find({}, {"page-size": 100});`

The second parameter is an object whose values are used as url params for requests to the REST API, so keys like `fields`, `sort`, and `page-state` are put there (you use page state to move the curser to the next page of results).

There is more info on those values here: https://docs.datastax.com/en/astra/docs/_attachments/docv2.html#operation/searchDoc

Thanks!

**Comment by adherb** [comment]
Fantastic, thanks so much Chris, appreciate it.

I couldn't find this docs, they are very helpful.

Thanks again,
Adam
