### ISSUE TITLE
Delete always returns null-response

### ISSUE THREAD

**Issue by Cahllagerfeld** [datastax/astrajs#9]
```ts
 async delete(path) {
    const response = await this.restClient.delete(`${this.basePath}/${path}`);
    if (response.status === 204) {
      return response.data;
    }
    return null;
  }
}
```
In the collection package `null` is returned if the response is not `204`

The problem is that Stargate returns a `null`-Response as well if the status code is `204`

![image](https://user-images.githubusercontent.com/43843195/117121818-6cade480-ad95-11eb-9c58-2ddcffd2d139.png)

This makes it hard to react if the deletion was successfull or not

**Comment by kidrecursive** [comment]
Ah, yes, we should return something different then null if the delete is successful. I'm thinking:

```javascript
{
  "documentId": ...,
  "deleted": true
}
```

**Comment by Cahllagerfeld** [comment]
That would be nice!

**Comment by kidrecursive** [comment]
This is now in v0.0.14 https://www.npmjs.com/package/@astrajs/collections

**Comment by Cahllagerfeld** [comment]
Nice, I'll bump my version 👍
